'use client';

import React, { useState, useEffect } from 'react';
import CampGhidat from './CampGhidat';

export type FieldDef = {
  id: string;
  label: string;
  placeholder: string;
  aiConfig?: any;
};

export type ParagrafText = {
  titlu: string;
  text: string;
};

export type CapitolProps = {
  nr: number;
  title: string;
  fields?: FieldDef[];
  state: any;
  rez: any;
  onAssemble?: (fieldsData: any, state: any, rez: any) => ParagrafText[];
  isAutoGenerated?: boolean;
  isBlocked?: boolean;
  blockedMessage?: string;
  children?: React.ReactNode;
  onComplete?: (status: boolean) => void;
};

export default function Capitol({ nr, title, fields = [], state, rez, onAssemble, isAutoGenerated, isBlocked, blockedMessage, children, onComplete }: CapitolProps) {
  const [formData, setFormData] = useState<Record<string, string>>({});
  const [assembledData, setAssembledData] = useState<ParagrafText[] | null>(null);
  const [isSaved, setIsSaved] = useState(false);
  const [isExpanded, setIsExpanded] = useState(true);

  useEffect(() => {
    const savedForm = localStorage.getItem(`cap_${nr}_form`);
    if (savedForm) setFormData(JSON.parse(savedForm));
    const savedAss = localStorage.getItem(`cap_${nr}_ass`);
    if (savedAss) setAssembledData(JSON.parse(savedAss));
    const savedState = localStorage.getItem(`cap_${nr}_saved`);
    if (savedState === 'true' || isAutoGenerated) {
      setIsSaved(true);
      setIsExpanded(false);
      onComplete?.(true);
    }
  }, [nr, onComplete]);

  const saveToLocal = (form: any, ass: any, saved: boolean) => {
    localStorage.setItem(`cap_${nr}_form`, JSON.stringify(form));
    localStorage.setItem(`cap_${nr}_ass`, ass ? JSON.stringify(ass) : '');
    localStorage.setItem(`cap_${nr}_saved`, saved ? 'true' : 'false');
  };

  const handleFieldChange = (id: string, val: string) => {
    const nou = { ...formData, [id]: val };
    setFormData(nou);
    saveToLocal(nou, assembledData, isSaved);
  };

  const handleAssemble = () => {
    if (onAssemble) {
      const result = onAssemble(formData, state, rez);
      setAssembledData(result);
      setIsSaved(false);
      saveToLocal(formData, result, false);
      onComplete?.(false);
    }
  };

  const handleParagrafChange = (idx: number, newText: string) => {
    if (!assembledData) return;
    const newData = [...assembledData];
    newData[idx].text = newText;
    setAssembledData(newData);
    saveToLocal(formData, newData, isSaved);
  };

  const handleSalvare = () => {
    setIsSaved(true);
    setIsExpanded(false);
    saveToLocal(formData, assembledData, true);
    onComplete?.(true);
  };

  const handleReincepe = () => {
    setAssembledData(null);
    setIsSaved(false);
    setIsExpanded(true);
    saveToLocal(formData, null, false);
    onComplete?.(false);
  };

  const isCompletat = fields.every(f => (formData[f.id] || '').trim().length > 0);

  let headerColor = '#111827';
  if (isSaved) headerColor = '#0f766e';
  else if (isCompletat) headerColor = '#ca8a04'; // yellow

  return (
    <div style={{ padding: '24px', backgroundColor: '#fff', borderRadius: '8px', boxShadow: '0 1px 3px rgba(0,0,0,0.1)', marginBottom: '24px' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px' }}>
        <h2 style={{ fontSize: '1.25rem', fontWeight: 600, color: headerColor, margin: 0 }}>
          {nr}. {title} {isSaved && '✓'}
        </h2>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
          {children}

          {!children && !isAutoGenerated && fields.map(f => (
            <CampGhidat
              key={f.id}
              label={f.label}
              placeholder={f.placeholder}
              value={formData[f.id] || ''}
              onChange={(val) => handleFieldChange(f.id, val)}
              aiConfig={f.aiConfig}
            />
          ))}

          {!children && !isAutoGenerated && onAssemble && !assembledData && (
            <button
              onClick={handleAssemble}
              disabled={isBlocked}
              style={{
                backgroundColor: isBlocked ? '#9ca3af' : '#0f766e', color: 'white', padding: '12px 24px', borderRadius: '6px',
                fontWeight: 600, border: 'none', cursor: isBlocked ? 'not-allowed' : 'pointer', fontSize: '1rem', width: '100%', marginTop: '8px'
              }}
            >
              Asamblează capitolul
            </button>
          )}

          {isBlocked && blockedMessage && (
            <div style={{ padding: '12px', backgroundColor: '#fffbeb', color: '#92400e', borderRadius: '6px', fontSize: '0.9rem', border: '1px solid #fde68a', marginTop: '12px' }}>
              {blockedMessage}
            </div>
          )}

          {assembledData && (
            <div style={{ marginTop: '16px', borderTop: '1px solid #e5e7eb', paddingTop: '16px' }}>
              <h3 style={{ fontSize: '1.1rem', fontWeight: 600, color: '#111827', marginBottom: '16px' }}>Text asamblat:</h3>
              
              <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
                {assembledData.map((paragraf, i) => (
                  <div key={i}>
                    <h4 style={{ fontSize: '0.95rem', fontWeight: 600, color: '#374151', marginBottom: '8px' }}>{paragraf.titlu}</h4>
                    <textarea
                      value={paragraf.text}
                      onChange={(e) => handleParagrafChange(i, e.target.value)}
                      style={{
                        width: '100%', minHeight: '120px', padding: '12px 16px', borderRadius: '0 6px 6px 0',
                        border: '1px solid #d1d5db', borderLeft: '4px solid #0f766e', fontSize: '1rem',
                        lineHeight: 1.8, color: '#1f2937', fontFamily: 'inherit', resize: 'vertical'
                      }}
                    />
                  </div>
                ))}
              </div>

              <div style={{ display: 'flex', gap: '12px', marginTop: '24px' }}>
                <button
                  onClick={handleSalvare}
                  style={{
                    flex: 1, backgroundColor: '#0f766e', color: 'white', padding: '10px',
                    borderRadius: '6px', fontWeight: 600, border: 'none', cursor: 'pointer'
                  }}
                >
                  ✓ Salvează capitol
                </button>
                <button
                  onClick={handleReincepe}
                  style={{
                    backgroundColor: '#f3f4f6', color: '#4b5563', padding: '10px 20px',
                    borderRadius: '6px', fontWeight: 600, border: '1px solid #d1d5db', cursor: 'pointer'
                  }}
                >
                  ↺ Reîncepe
                </button>
              </div>
            </div>
          )}
        </div>
    </div>
  );
}
